# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Downtown
tagline:          "Sinae's Blog"
description:      ''
url:              http://sinae-hong.github.io
baseurl:          

author:
  name:           'Sinae Hong'

plugins:
  - jekyll-paginate
  - jekyll-gist
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sinae-hong/sinae-hong.github.io
